settings:
  texts: # Сообщения, которые будут отправлены при покупке доната
    1:
      - ""
      - "&7╔ &fИгрок &6%player% &fкупил %donate%"
      - "&7║ &fНа нашем сайте &6www.yourmine.ru"
      - "&7╚ &fКупил он - купи и ты!"
      - ""
    2:
      - ""
      - "&7╔ &fИгрок &6%player% &fкупил %donate%"
      - "&7║ &fНа нашем сайте &6www.yourmine.ru"
      - "&7╚ &fБлагодарим от лица всей администрации!"
      - ""
    3:
      - ""
      - "&7╔ &fИгрок &6%player% &fкупил %donate%"
      - "&7║ &fНа нашем сайте &6www.yourmine.ru"
      - "&7╚ &fПрячься, тебя сегодня кто-то найдет!"
      - ""
  enable-title: true # Включить ли тайтлы при покупке доната?
  title: "&6&lДОНАТ" # Тайтл
  sub-title: "&6%player% &fкупил %donate%&f!" # Субтайтл
telegram:
  settings:
    enable: true # Включить ли отправку оповещения в телеграмм о покупке доната?
    bot-token: "token" # Токен бота
    bot-username: "username_bot" # Username бота
    admin-chat-ids: # ChatId администраторов, которым будет приходить уведомления
      - "1111111111"
  messages:
    notify-donate: # Сообщение с уведомлением о покупке
      - "⚠ Оповещение о покупке! ⚠"
      - ""
      - "╔ Игрок: %player%"
      - "║ Продукт: %donate%"
      - "╚ Дата: %date%"
vk:
  settings:
    enable: true # Включить ли отправку сообщений в вк о покупке доната?
    groupId: "111111111" # Айди группы
    accessToken: "token" # Токен группы
    admin-user-ids: # UserId администраторов, которым будет приходить уведомления
      - "111111111"
  messages:
    notify-donate: # Сообщение с уведомлением о покупке
      - "⚠ Оповещение о покупке! ⚠"
      - ""
      - "╔ Игрок: %player%"
      - "║ Продукт: %donate%"
      - "╚ Дата: %date%"
messages:
  reload: "&fВы перезагрузили плагин!" # Сообщение о перезагрузке плагина
  no-permission: "&fУ Вас нет прав!" # Сообщение о нехватке прав
  help: # Сообщение, когда игрок не так написал аргументы команды
    - "&fПомощь по плагину &6fmDonateAlert&f:"
    - ""
    - "&6/fmdonatealert reload &7- &fперезагрузить плагин"
    - "&6/fmdonatealert alert &7(&6ник&7) (&6донат&7) - &fвыслать сообщение о покупке доната"
  alert: "&fВы успешно выслали уведомление о покупке доната!" # Сообщение, когда игрок выслал уведомление о покупке доната